window.imoveis = [
  {
    id: 1,
    isDefault: true,
    nome: "Alameda Jardins",
    construtora: "FG",
    localizacao: "Centro, Balneário Camboriú",
    preco: "R$ 5.990.000,00",
    quartos: 4,
    suites: 4,
    vagas: 3,
    areaUtil: "170 m²",
    areaTotal: "170 m²",
    imagem: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
    badge: "Exclusividade",
    tipo: "Apartamento",
    finalidade: "Compra",
    descricao: "Apartamento de alto padrão no coração de Balneário Camboriú, com vista definitiva para o mar. Acabamentos impecáveis e área de lazer completa em um dos endereços mais cobiçados da cidade.",
    youtube: ""
  },
  {
    id: 2,
    isDefault: true,
    nome: "Ocean View",
    construtora: "Embraed",
    localizacao: "Barra Sul, Balneário Camboriú",
    preco: "R$ 8.500.000,00",
    quartos: 5,
    suites: 5,
    vagas: 4,
    areaUtil: "250 m²",
    areaTotal: "250 m²",
    imagem: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    badge: "Alto Padrão",
    tipo: "Cobertura",
    finalidade: "Compra",
    descricao: "Cobertura duplex espetacular na Barra Sul. Piscina privativa, amplo terraço e living integrado com vista panorâmica de 360º para a orla de BC e Marina.",
    youtube: ""
  },
  {
    id: 3,
    isDefault: true,
    nome: "Residencial Marbella",
    construtora: "Silva & Silva",
    localizacao: "Pioneiros, Balneário Camboriú",
    preco: "R$ 15.000,00 / mês",
    quartos: 3,
    suites: 1,
    vagas: 2,
    areaUtil: "120 m²",
    areaTotal: "120 m²",
    imagem: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800",
    badge: "Locação",
    tipo: "Apartamento",
    finalidade: "Locação",
    descricao: "Excelente apartamento para locação anual, finamente mobiliado, a poucos passos da praia e da nova Roda Gigante. Lazer completo no condomínio.",
    youtube: ""
  },
  {
    id: 4,
    isDefault: true,
    nome: "Casa Alphaville",
    construtora: "Particular",
    localizacao: "Alphaville, Camboriú",
    preco: "R$ 4.200.000,00",
    quartos: 4,
    suites: 4,
    vagas: 4,
    areaUtil: "350 m²",
    areaTotal: "350 m²",
    imagem: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    badge: "Oportunidade",
    tipo: "Casa",
    finalidade: "Compra",
    descricao: "Casa em condomínio fechado com projeto arquitetônico contemporâneo. Espaço gourmet amplo e integração perfeita com a natureza, oferecendo tranquilidade e segurança.",
    youtube: ""
  },
  {
    id: 5,
    isDefault: true,
    nome: "Corporate Tower",
    construtora: "FG",
    localizacao: "Centro, Balneário Camboriú",
    preco: "R$ 1.200.000,00",
    quartos: 0,
    suites: 0,
    vagas: 1,
    areaUtil: "65 m²",
    areaTotal: "65 m²",
    imagem: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
    badge: "Comercial",
    tipo: "Sala Comercial",
    finalidade: "Compra",
    descricao: "Sala comercial de alto padrão em edifício corporativo moderno. Localização estratégica no centro comercial, ideal para clínicas, escritórios jurídicos ou startups.",
    youtube: ""
  },
  {
    id: 6,
    isDefault: true,
    nome: "Brava Arts",
    construtora: "Lotisa",
    localizacao: "Praia Brava, Itajaí",
    preco: "R$ 3.750.000,00",
    quartos: 3,
    suites: 3,
    vagas: 2,
    areaUtil: "145 m²",
    areaTotal: "145 m²",
    imagem: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&q=80&w=800",
    badge: "Mobiliado",
    tipo: "Apartamento",
    finalidade: "Compra",
    descricao: "Apartamento mobiliado na Praia Brava, com living integrado, sacada ampla e uma localização perfeita para quem busca praia, gastronomia e praticidade no dia a dia.",
    youtube: ""
  },
  {
    id: 7,
    isDefault: true,
    nome: "Mansion Horizon",
    construtora: "Pasqualotto&GT",
    localizacao: "Barra Sul, Balneário Camboriú",
    preco: "R$ 12.500.000,00",
    quartos: 5,
    suites: 5,
    vagas: 4,
    areaUtil: "320 m²",
    areaTotal: "320 m²",
    imagens: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800"
    ],
    badges: ["Alto Padrão", "Frente Mar", "Lançamento"],
    tipo: "Apartamento",
    finalidade: "Compra",
    descricao: "Mansão suspensa de frente para o mar na cobiçada Barra Sul. O Horizon oferece um living expansivo de 100m² totalmente envidraçado, suíte master com spa privado e acabamentos de altíssimo padrão com mármore importado. Conta ainda com automação residencial completa e infraestrutura de lazer incomparável, incluindo heliponto e marina privativa.",
    youtube: ""
  },
  {
    id: 8,
    isDefault: true,
    nome: "Reserva da Brava",
    construtora: "PROCAVE",
    localizacao: "Praia Brava, Itajaí",
    preco: "R$ 7.900.000,00",
    quartos: 4,
    suites: 4,
    vagas: 3,
    areaUtil: "210 m²",
    areaTotal: "210 m²",
    imagens: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&q=80&w=800"
    ],
    badges: ["Exclusividade", "Decorado"],
    tipo: "Cobertura",
    finalidade: "Compra",
    descricao: "Cobertura finamente decorada por arquitetos de renome, localizada na vibrante Praia Brava. O espaço conta com piscina privativa aquecida de borda infinita, terraço gourmet equipado e móveis assinados. Um verdadeiro oásis urbano a poucos passos da areia e cercado pela natureza intocada.",
    youtube: ""
  },
  {
    id: 9,
    isDefault: true,
    nome: "Villa Toscana",
    construtora: "Particular",
    localizacao: "Estaleiro, Balneário Camboriú",
    preco: "R$ 18.000.000,00",
    quartos: 6,
    suites: 6,
    vagas: 6,
    areaUtil: "850 m²",
    areaTotal: "850 m²",
    imagens: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=800"
    ],
    badges: ["Oportunidade", "Mobiliado"],
    tipo: "Casa",
    finalidade: "Compra",
    descricao: "Magnífica casa de praia em estilo toscano na exclusiva praia do Estaleiro. Com um terreno de 2000m², a propriedade conta com adega subterrânea climatizada, cinema privado para 12 pessoas, quadra de tênis, horta orgânica e um projeto paisagístico espetacular. Totalmente mobiliada e equipada com eletrodomésticos de primeira linha.",
    youtube: ""
  },
  {
    id: 10,
    isDefault: true,
    nome: "Sky Garden Corporate",
    construtora: "FG",
    localizacao: "Centro, Balneário Camboriú",
    preco: "R$ 2.450.000,00",
    quartos: 0,
    suites: 0,
    vagas: 2,
    areaUtil: "120 m²",
    areaTotal: "120 m²",
    imagens: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800"
    ],
    badges: ["Comercial", "Lançamento"],
    tipo: "Sala Comercial",
    finalidade: "Compra",
    descricao: "O ápice do luxo corporativo. Sala comercial de canto com vista espetacular para o mar e para a cidade, ideal para sedes de grandes empresas ou clínicas premium. O empreendimento oferece auditório, salas de reuniões inteligentes, heliponto homologado e certificação LEED de sustentabilidade.",
    youtube: ""
  },
  {
    id: 11,
    isDefault: true,
    nome: "Península Resort",
    construtora: "Embraed",
    localizacao: "Barra Sul, Balneário Camboriú",
    preco: "R$ 45.000,00 / mês",
    quartos: 4,
    suites: 4,
    vagas: 3,
    areaUtil: "280 m²",
    areaTotal: "280 m²",
    imagens: [
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800"
    ],
    badges: ["Locação", "Frente Mar", "Decorado"],
    tipo: "Apartamento",
    finalidade: "Locação",
    descricao: "Apartamento de luxo para locação anual. Decoração minimalista sofisticada, automação completa de iluminação e som, e varanda gourmet. O condomínio é um verdadeiro resort particular, com 5 piscinas, spa L'Occitane, restaurante exclusivo para moradores, quadras esportivas e serviço de concierge 24h.",
    youtube: ""
  },
  {
    id: 12,
    isDefault: true,
    nome: "Acqua Infinity",
    construtora: "Cechinel",
    localizacao: "Barra Norte, Balneário Camboriú",
    preco: "R$ 9.200.000,00",
    quartos: 4,
    suites: 4,
    vagas: 4,
    areaUtil: "245 m²",
    areaTotal: "245 m²",
    imagens: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600573472550-80905ca12435?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80&w=800"
    ],
    badges: ["Exclusividade", "Alto Padrão"],
    tipo: "Apartamento",
    finalidade: "Compra",
    descricao: "Empreendimento ícone na Barra Norte. O Acqua Infinity destaca-se por sua arquitetura arrojada e vistas deslumbrantes da orla. Este apartamento conta com living integrado à sacada panorâmica, suíte master com mais de 40m², adega embutida e acabamentos em lâmina natural de madeira e pedras exóticas. A área de lazer inclui piscina aquecida com raia de 25m e academia Life Fitness.",
    youtube: ""
  }
];
